\htgt{ReadStatement} ::=\\
\x \kw{READ} [ \{ Name$\S $Variable $\mid$ \hlink{ArraySlice} \} 
	[ \kw{,} \{ Name$\S $Variable $\mid$ \hlink{ArraySlice} \} ] $^{...}$ ]\\
\x \kw{FROM} \hlink{Name}$\S $Dation 
	[ \kw{BY} \hlink{Position} [ \kw{,} \hlink{Position} ] $^{...}$ ] \kw{;}

      
