// [automatic generated by intermodule checker (imc v3) -- do not change ]
// 2020/08/24 09:05:51
// use of namespace is: false

#include "PearlIncludes.h" 



namespace pearlrt {
   int createSystemElements();
}

// enshure that the static (parametrized) objects are instantiated first
static int dummy = pearlrt::createSystemElements();

	pearlrt::Device *  d_stdout;		// hello.prl:8



namespace pearlrt {
   int createSystemElements() {
	// hello.prl:8
	static pearlrt::StdOut s_stdout;
	d_stdout= &s_stdout;


	return 0;
   }
}
