// [automatic generated by intermodule checker (imc v3) -- do not change ]
// 2020/01/08 14:41:29
// use of namespace is: false

#include "PearlIncludes.h" 



namespace pearlrt {
   int createSystemElements();
}

// enshure that the static (parametrized) objects are instantiated first
static int dummy = pearlrt::createSystemElements();

	pearlrt::Device *  d_stdOut;		// demo1.prl:14
	pearlrt::Device *  d_rpiBi3;		// demo1.prl:400
	pearlrt::Device *  d_bit1;		// demo1.prl:200
	pearlrt::Device *  d_bit2;		// demo1.prl:201
	pearlrt::Device *  d_bitout;		// demo1.prl:202
	pearlrt::Device *  d_lm75;		// demo1.prl:4
	static pearlrt::FixedRangeSignal _sig1;		// demo1.prl:9
	pearlrt::Signal generalized_sig1= & _sig1;

	pearlrt::Interrupt *_int1;		// demo1.prl:10
	pearlrt::Device *  d_disc;		// demo1.prl:12



namespace pearlrt {
   int createSystemElements() {
	// demo1.prl:14
	static pearlrt::StdOut s_stdOut;
	d_stdOut= &s_stdOut;

	// demo1.prl:16
	static pearlrt::Log configurarion_0(& s_stdOut, (char*)"EW");
	// demo1.prl:400
	static pearlrt::RPiDigitalIn s_rpiBi3(9, 2, (char*)"n");
	d_rpiBi3= &s_rpiBi3;

	// demo1.prl:7
	static pearlrt::I2CBus s_i2cbus1((char*)"/dev/i2c-1");
	// demo1.prl:200
	static pearlrt::PCF8574In s_bit1(& s_i2cbus1, 0x20, 2, 2);
	d_bit1= &s_bit1;

	// demo1.prl:7
	static pearlrt::I2CBus s_i2cbus0((char*)"/dev/i2c-0");
	// demo1.prl:201
	static pearlrt::PCF8574In s_bit2(& s_i2cbus0, 0x20, 2, 1);
	d_bit2= &s_bit2;

	// demo1.prl:202
	static pearlrt::PCF8574Out s_bitout(& s_i2cbus1, 0x20, 0, 1);
	d_bitout= &s_bitout;

	// demo1.prl:4
	static pearlrt::I2CBus sautoNameForAssociation_0((char*)"/dev/i2c-2");
	// demo1.prl:4
	static pearlrt::LM75 s_lm75(& sautoNameForAssociation_0, 0x49);
	d_lm75= &s_lm75;

	// demo1.prl:10
	static pearlrt::UnixSignal sys_int1(15);
	_int1= (pearlrt::Interrupt*) &sys_int1;

	// demo1.prl:12
	static pearlrt::Disc s_disc((char*)"/tmp/folder1", 10);
	d_disc= &s_disc;


	return 0;
   }
}
